Seems to fix herberttn/bytenode-webpack-plugin#5
herberttn/bytenode-webpack-plugin pull request #7
Opened 2021-07-18 11:40 UTC by cfadams

Webpack 5 seems to pass through entrypoint paths with a more complex data structure, e.g. in an Electron context:
`[{
  main_window: {
    import: ['./src/index.ts']
  }
}]`

Whereas the plugin would expect:
`[{ main_window: './src/index.ts' }]`

These commits add in some extra data manipulation to give the plugin the file paths as expected.

Todo:
- [ ] Dig out the Webpack docs/spec to ensure these fixes are compatible with all potential entry inputs
- [ ] Test extensively with more than just an electron-forge + TS + Webpack template app

2021-07-19 22:48 UTC, dopry commented
@cfadams on the surface this looks good. Can you address the lint errors?

2021-07-19 22:54 UTC, dopry commented on src/index.ts
> +function prepare(context: string | undefined, location: string | string[] | { import: string } | { import: string }[], name?: string, suffix = ''): Prepared {
It might make sense to have Webpack4Location and Webpack5Location types to help document these structures?

2021-07-19 22:54 UTC, dopry commented on src/index.ts
> +      if (typeof location === 'object' && location.import) {
we should probably also comment why we have these conditionals in place and what they're meant to determine or substitute an isWebpack4Location(location)  and isWebpack5Location(location) to make the code self-documenting.

2021-07-21 21:48 UTC, herberttn requested changes
Hi @cfadams, thank you for the contribution!

Can we have types and comments to more easily differentiate behaviors and structures of v4 and v5? Right now everything works on v4 only, so would be useful to better understand everything as we begin branching out the logic.

2021-08-17 10:12 UTC, Auxxxxlx commented
I tested this PR manually,  and got this error:
![image](https://user-images.githubusercontent.com/13865581/129707896-68c9cc81-632c-4f9b-88c9-851e793b29c3.png)

2021-08-17 23:41 UTC, mmaietta commented
Same as ☝️ 

More error logs to help debug:
```
ERROR in main
Module not found: Error: Can't resolve './src' in '/Users/janedoe/Development/shell'
resolve './src' in '/Users/janedoe/Development/shell'
  using description file: /Users/janedoe/Development/shell/package.json (relative path: .)
    using description file: /Users/janedoe/Development/shell/package.json (relative path: ./src)
      no extension
        /Users/janedoe/Development/shell/src is not a file
      .js
        /Users/janedoe/Development/shell/src.js doesn't exist
      .ts
        /Users/janedoe/Development/shell/src.ts doesn't exist
      .node
        /Users/janedoe/Development/shell/src.node doesn't exist
      as directory
        existing directory /Users/janedoe/Development/shell/src
          using description file: /Users/janedoe/Development/shell/package.json (relative path: ./src)
            using path: /Users/janedoe/Development/shell/src/index
              using description file: /Users/janedoe/Development/shell/package.json (relative path: ./src/index)
                no extension
                  /Users/janedoe/Development/shell/src/index doesn't exist
                .js
                  /Users/janedoe/Development/shell/src/index.js doesn't exist
                .ts
                  /Users/janedoe/Development/shell/src/index.ts doesn't exist
                .node
                  /Users/janedoe/Development/shell/src/index.node doesn't exist
```
Relevant config:
```
merge.smart(baseConfig, {
    target: "electron-main",
    entry:  { 
        main: "src/main/index.ts",
    },
    node: {
        __dirname: false,
        __filename: false
    },
    output: {
        path: path.join(__dirname, "out", "main"),
        libraryTarget: "commonjs"
    },
    plugins: [
        new BytenodeWebpackPlugin({
            compileForElectron: true
        })
    ]
})
```

2021-09-22 07:07 UTC, Zomono commented
Does anyone work on this PR? 
If not: What should be done to merge this PR?

2021-09-22 07:27 UTC, Alecyrus commented
> Does anyone work on this PR?
> If not: What should be done to merge this PR?

The PR does not solve the problem, it should not be merged.

2021-10-05 12:03 UTC, cfadams commented
Agreed with @dopry that knowledge of Webpack 5 is needed to get this over the line. Happy to close and abort this PR given this isn't a solution?

2021-10-05 14:02 UTC, dopry commented
@cfadams  lets keep this open a as a work space for now, so the discussion doesn't get split...

I did find https://github.com/webpack/webpack/issues/11425, which seems to indicate we should be using the processAssets instead of emit.

2022-10-20 05:49 UTC, herberttn commented
https://github.com/herberttn/bytenode-webpack-plugin/releases/tag/v2.0.0

2022-10-20 05:49 UTC, closed without merging